default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: simple_form_sandbox_development

test:
  <<: *default
  database: simple_form_sandbox_test

production:
  url: <%= ENV['DATABASE_URL'] %>
